# Generated by Django 4.0.2 on 2022-05-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_menu',
            old_name='m_menu_id',
            new_name='mainmenu_id',
        ),
        migrations.RenameField(
            model_name='main_menu',
            old_name='m_menu_link',
            new_name='menulink',
        ),
        migrations.RenameField(
            model_name='main_menu',
            old_name='m_menu_name',
            new_name='menuname',
        ),
        migrations.RenameField(
            model_name='sub_menu',
            old_name='m_menu_id',
            new_name='mainmenu_id',
        ),
        migrations.RenameField(
            model_name='sub_menu',
            old_name='s_menu_id',
            new_name='submen_id',
        ),
        migrations.RenameField(
            model_name='sub_menu',
            old_name='s_menu_link',
            new_name='submen_link',
        ),
        migrations.RenameField(
            model_name='sub_menu',
            old_name='s_menu_name',
            new_name='submen_name',
        ),
    ]
