# Generated by Django 4.0.2 on 2022-05-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('descp', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
