# Generated by Django 4.0.2 on 2022-05-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
